# Wrangler configuration for parking-app-api
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "parking-app-api"
main = "src/index.ts"
compatibility_date = "2025-07-15"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "parking-permits-db"
database_id = "2ed67dad-d2b2-47c6-9b32-b817cd1475cb"
